### ISSUE TITLE
Unresolved reference: println

### ISSUE THREAD

**Issue by Gabgab2003** [fwcd/vscode-kotlin-ide#10]
I just installed this and I have a file that is only a main function with println, the extension however tells me  "Unresolved reference: println", im sure this is a mistake on my side. I tried with the kotlin and kotlinc binaries in the path (im on windows 10 18362). Help would be much apreciated

**Comment by fwcd** [comment]
This was fixed in https://github.com/fwcd/kotlin-language-server/pull/154, but hasn‘t been released yet. In the meantime, you could try a Kotlin project that uses Gradle, e.g. [kotlin-quick-start](https://github.com/fwcd/kotlin-quick-start).
