### ISSUE TITLE
How to support gradle kotlin scripts?

### ISSUE THREAD

**Issue by gdurand** [fwcd/vscode-kotlin-ide#13]
Hello,
I'd like to use VSCode to edit gradle kotlin scripts in projects that are not kotlin projects.
The syntax highlighting works, but of course the gradle DSL is not found so there are errors everywhere.

Is there a way to declare dependencies such as the gradle DSL?

**Comment by fwcd** [comment]
Was fixed by https://github.com/fwcd/kotlin-language-server/pull/157, but is not on the marketplace yet.
