### ISSUE TITLE
Support for syntax highlighting in markdown documents

### ISSUE THREAD

**Issue by ghuser** [fwcd/vscode-kotlin-ide#27]
**Is your feature request related to a problem? Please describe.**
The following section is not highlighted in an `.md` document 

```kotlin
> ```kotlin
> var x=3
> ```
```

**Describe the solution you'd like**
Sytax highlighting support for kotlin in markdown documents.

**Describe alternatives you've considered**

**Additional context**

**Comment by fwcd** [comment]
This seems to be a limitation of VSCode, since the grammars supported by fenced code blocks are [baked into the Markdown grammar](https://github.com/microsoft/vscode-markdown-tm-grammar/blob/9a3d476b61c931ec4c6488cc68cbfc6c6f86334b/syntaxes/markdown.tmLanguage#L2753-L2956).

**Comment by fwcd** [comment]
Fixed by https://github.com/fwcd/kotlin-language-server/commit/3a4c0640c6f8462ee4e5eb49fc431e480408a4f0 and d7aa439ee84d8e2c78e5b5a45c311051a62b644e.
