### ISSUE TITLE
The extension downloads binaries without asking

### ISSUE THREAD

**Issue by marmistrz** [fwcd/vscode-kotlin-ide#7]
It's ok to provide easy onboarding, but the extension should ask before downloading anything. What if the user is on a metered connection or prefers to install the Kotlin Language Server themselves.

That's what the official Rust Language Server extension for VS Code does.

**Comment by fwcd** [comment]
The extension does provide the options `kotlin.languageServer.enabled` and `kotlin.debugAdapter.enabled` which fully disable any downloads. These can be set before a Kotlin file is opened.

Also, `kotlin.languageServer.path` and `kotlin.debugAdapter.path` can be pointed to a custom binary.

I agree, though, some confirmation prompt would probably be better.

**Comment by fwcd** [comment]
@marmistrz The extension will now show the following notification before downloading anything:

![grafik](https://user-images.githubusercontent.com/30873659/64283473-d0946000-cf57-11e9-9a9e-eedbd41d30a3.png)

**Comment by marmistrz** [comment]
I guess that it would probably be a better UX to expose a "no" button, the X is not very visible at first glance. But it's basically that :)
